### ISSUE TITLE
Deploy bot to Oracle Server

### ISSUE THREAD

**Issue by Ziggiyzoo** [Ziggiyzoo/StarCitizenOrg-Discord-Bot#11]

**Comment by Renegade-Master** [comment]
Oh, I see. Didn't realise I had been assigned to this.

Well, once we have the '[Push New Version](https://github.com/Ziggiyzoo/BRVNS-Discord-Bot/actions/workflows/push_new_version.yml)' Action working, I should be able to make Docker Images, and publish them to the [GH Packages](https://github.com/Ziggiyzoo?tab=packages&repo_name=BRVNS-Discord-Bot) page. I have already set the server up with Podman (I think), so it should just be a case of running the Image as a Container once we have the Image published.

**Comment by Renegade-Master** [comment]
#17 will help to resolve this.
